# Generated by Django 4.1.5 on 2023-01-22 23:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="name",
        ),
        migrations.AddField(
            model_name="person",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="server",
            name="clientId",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="server",
            name="clientSecret",
            field=models.TextField(
                default=datetime.datetime(
                    2023, 1, 22, 23, 12, 13, 957062, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
