# Generated by Django 4.1.5 on 2023-02-07 17:30

from django.db import migrations, models
from django.apps import apps

def populateTestServer(apps, schema_editor):
    Data = apps.get_model('api', 'Server')
    Data.objects.create(
        serverId='1055189024228257833',
        channelName='get-verified',
        roleName='Verified',
        clientId='SERVER_XXMCF1KO8QHT38CXQBC6RV',
        clientSecret='BXO2ULuFJry9FSzfUzQyxoNqlO_w0mQIbZM1tOXim3uaWdcqzMikSxNdHpiD153n',
    )

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_person_name_person_created_server_clientid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populateTestServer),
    ]
