# Generated by Django 4.2.4 on 2023-08-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_serverid_request_serverid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='serverID',
            new_name='serverId',
        ),
    ]
