# Generated by Django 4.1.5 on 2023-02-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_person_name_person_created_server_clientid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
