# Generated by Django 4.1.5 on 2023-04-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_person_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="userId",
            new_name="requestId",
        ),
    ]
