# Generated by Django 5.0.4 on 2024-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_serverid_request_serverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='clientEmail',
            field=models.TextField(null=True),
        ),
    ]
