# Generated by Django 4.1.5 on 2023-05-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_userid_person_requestid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="channelName",
            field=models.TextField(default="get-verified"),
        ),
        migrations.AlterField(
            model_name="server",
            name="roleName",
            field=models.TextField(default="Verified"),
        ),
    ]
