FROM node:20-alpine as build

WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . /app

RUN npm run build

FROM nginx:alpine as deploy

WORKDIR /usr/share/nginx/html

COPY --from=build /app/build /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/nginx.conf