version: '3.7'
services:
  bot:
    container_name: discord_bot
    build:
      context: ./bot
      dockerfile: dockerfile
    env_file:
      - ./bot/.env
    networks:
      - human_id
    volumes:
      - ./bot/discordbot.py:/bot/discordbot.py

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - human_id
    volumes:
      - ./frontend/src:/app/src

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - human_id
    volumes:
      - ./backend/api:/code/api
      - ./backend/backend:/code/backend
      - ./backend/sql:/code/sql

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - human_id

networks:
  human_id:
    driver: bridge
