import requests

# url = requests.get('http://127.0.0.1:8000/api?serverId=1055189024228257833')
url = requests.get('http://127.0.0.1:8000/api/confirm/?requestId=3TAIHBTGUGQPTOADCF1ZMU2A')
print(url)

# # Generated by Django 4.2.3 on 2023-07-13 23:05

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ("api", "0005_alter_server_channelname_alter_server_rolename"),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name="Request",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 ("requestId", models.TextField()),
#                 ("userId", models.TextField()),
#                 ("created", models.DateTimeField(auto_now_add=True)),
#                 ("verified", models.BooleanField(default=False)),
#             ],
#         ),
#         migrations.RenameField(
#             model_name="person", old_name="requestId", new_name="humanUserId",
#         ),
#         migrations.RemoveField(model_name="person", name="created",),
#         migrations.RemoveField(model_name="person", name="verified",),
#         migrations.AddField(
#             model_name="person",
#             name="userId",
#             field=models.TextField(default=0),
#             preserve_default=False,
#         ),
#     ]

