DROP TABLE IF EXISTS server;
DROP TABLE IF EXISTS person;

CREATE TABLE person( userId VARCHAR(64) UNIQUE PRIMARY KEY NOT NULL, name VARCHAR(64) NOT NULL);

CREATE TABLE server( serverId VARCHAR(64) UNIQUE PRIMARY KEY NOT NULL, channelName VARCHAR(64) NOT NULL, roleName VARCHAR(64) NOT NULL);

