name: 00 - Main CI/CD Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
        uses: actions/checkout@v2

        - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
            run: |
                docker-compose build
                # Assuming you're also pushing the image to DockerHub
                docker-compose push 

        - name: Run Docker containers
            run: docker-compose up -d
    
    sast:
        needs: build
        name: 01 - Static Application Security Testing
        uses: ./.github/workflows/sast.yml
        secrets: inherit
    
