name: 20 - SAST Pipeline

# SAST Pipeline
on:
    workflow_dispatch:
    workflow_call:

jobs:
    SAST-CodeQL:
        name: SAST-CodeQL
        permissions:
            actions: read
            contents: read
            security-events: write
        runs-on: ubuntu-latest
                
        strategy:
            fail-fast: false
            matrix:
                language: ['javascript', 'python']

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Initialize CodeQL
            uses: github/codeql-action/init@v2
            with:
                languages: ${{ matrix.language }}

          - name: Analyze code with CodeQL
            uses: github/codeql-action/analyze@v2
            with:
                # Path to the CodeQL database
                database-path: codeql-database
                # Path to the SARIF file to be generated
                sarif-file: codeql-results.sarif